name: Create Kidase Slides from Google Form submission and Email to User

on:
  repository_dispatch:
    types: [form-submission]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Decode and save credentials.json
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" > encoded_credentials.txt
          python -c "import base64; import os; encoded = open('encoded_credentials.txt').read(); decoded = base64.b64decode(encoded); with open('credentials.json', 'wb') as f: f.write(decoded)"

      - name: Run script
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDR }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASS }}
        run: python create_slides.py
